/*
 * File-specific version information
 *
 * Put this file in the project directory for each
 * app/dll that will have a VERSIONINFO resource.
 */

//Include the file auto-generated by BuildVer app
#include "VerBuild.h"    

//Set to file-specific values
#define VER_FILE_DESCRIPTION ""
#define VER_INTERNAL_NAME    ""
#define VER_FILENAME         ""
